name: "action for git gc and BFG Repo-Cleaner"
description: "action for git gc and BFG Repo-Cleaner"
author: "ykla"
inputs:
  distribution:
    description: 'JDK Distribution'
    required: false
    default: 'oracle'
  file-size:
    description: 'file-size to clean'
    required: false
    default: '2M'
  java-version:
    description: 'JDK version'
    required: false
    default: '21'
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.distribution }} # See 'Supported distributions' for available options
        java-version: ${{ inputs.java-version }}
        
    - name: show java version
      shell: bash
      run: java -version
                
    - name: checkout mirror
      shell: bash
      run: |
          echo "-----------------------------------------"
          printf '%s\n' "NOW_REPOSITORY is $GH_ACTION_REPOSITORY" 
          printf '%s\n' "NOW_REPOSITORY_URL is $(echo "$GH_ACTION_GH_ACTION_REPOSITORY_URL" | sed "s#git://#https://#")"
          printf '%s\n' "NOW_REPOSITORY_NAME is ${GITHUB_REPOSITORY##*/}" 
          printf '%s\n' "FILE_SIZE is ${FILE_SIZE}" 
          pwd
          ls -l
          echo "-----------------------------------------"
          git clone --mirror $(echo "$GH_ACTION_GH_ACTION_REPOSITORY_URL" | sed "s#git://#https://#")
          curl -LJO https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar && [ -f "bfg-1.14.0.jar" ] && echo "Download successful: bfg-1.14.0.jar" || (echo "Download failed"; exit 1)
          ls -lk *.jar
          pwd
          java -jar bfg-1.14.0.jar --strip-blobs-bigger-than $FILE_SIZE ${GITHUB_REPOSITORY##*/}.git
          pwd
          du -sh ${GITHUB_REPOSITORY##*/}.git
          echo "--------GC----------------"
          cd ${GITHUB_REPOSITORY##*/}.git
          pwd
          ls
          git reflog expire --expire=now --all && git gc --prune=now --aggressive
          echo "------GC---OK-------------------------"
          git rebase --exec "git commit --amend --no-edit -n -S" -i --root
          git rebase --committer-date-is-author-date -i --root
          ls && pwd
          git push -f
          cd .. && du -sh ${GITHUB_REPOSITORY##*/}.git
          
          
      env:
        GH_ACTION_REPOSITORY: ${{ github.repository }}       
        GH_ACTION_GH_ACTION_REPOSITORY_URL: ${{ github.repositoryUrl }}      
        FILE_SIZE: ${{ inputs.file-size }}
        
